#!/usr/bin/env bash

SETTING_FILE="$1"
TARGET_PATH="$2"
shift 2 || true

if [[ -z "$SETTING_FILE" || -z "$TARGET_PATH" ]]; then
    echo "Usage: $0 <setting-file> <target> [extra-args...]" >&2
    exit 1
fi

exec "$HOME/.config/ml4w/scripts/ml4w-run-setting" "$SETTING_FILE" "$TARGET_PATH" "$@"
